// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// How far forward a window sits in the platform's stacking order.
enum KairoNativeWindowLevel {
  /// An ordinary application window, ordered against its siblings by use.
  normal,
  /// Above ordinary windows, including those of other applications. The
  /// character and reminder popups live here.
  floating,
  /// Behind every ordinary window, pinned to the desktop.
  desktop,
}

/// A rectangle in screen coordinates, in logical pixels.
///
/// A plain class rather than Flutter's `Rect`, because the generated Swift has
/// no access to Flutter's Dart types.
class KairoNativeRect {
  KairoNativeRect({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  double x;

  double y;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[
      x,
      y,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static KairoNativeRect decode(Object result) {
    result as List<Object?>;
    return KairoNativeRect(
      x: result[0]! as double,
      y: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KairoNativeRect || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) && _deepEquals(y, other.y) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KairoNativeRect(x: $x, y: $y, width: $width, height: $height)';
  }
}

/// Everything the platform needs in order to create a window.
///
/// Every field is required. Defaults belong to `KairoWindowDescriptor` on the
/// Dart side, where they can be documented and tested; a schema that also
/// carries them would be a second place for them to disagree.
class KairoNativeWindowSpec {
  KairoNativeWindowSpec({
    required this.entrypoint,
    required this.width,
    required this.height,
    required this.title,
    required this.level,
    required this.transparent,
    required this.decorated,
    required this.resizable,
    required this.ignoresMouseEvents,
    required this.skipTaskbar,
    this.x,
    this.y,
  });

  /// The Dart entrypoint the window's own engine runs.
  ///
  /// Every window gets a separate `FlutterEngine`, and so a separate isolate.
  /// The named function must be annotated `@pragma('vm:entry-point')`, or the
  /// compiler will discard it from a release build.
  String entrypoint;

  /// The window's initial width, in logical pixels.
  double width;

  /// The window's initial height, in logical pixels.
  double height;

  /// The window's title.
  ///
  /// Not drawn when [decorated] is false, but still what the platform reports
  /// to accessibility tools and window lists.
  String title;

  /// Where the window sits in the stacking order.
  KairoNativeWindowLevel level;

  /// Whether the window's background is transparent rather than opaque.
  ///
  /// This is what lets the character appear to stand on the desktop instead of
  /// inside a rectangle.
  bool transparent;

  /// Whether the platform draws a title bar and frame around the window.
  bool decorated;

  /// Whether the user may resize the window.
  bool resizable;

  /// Whether clicks fall through the window to whatever is behind it.
  ///
  /// A character that could not be clicked through would cover part of the
  /// screen the user is trying to work in.
  bool ignoresMouseEvents;

  /// Whether the window is hidden from the dock, taskbar and window switcher.
  bool skipTaskbar;

  /// The initial left edge, in screen coordinates. Centred when null.
  double? x;

  /// The initial top edge, in screen coordinates. Centred when null.
  double? y;

  List<Object?> _toList() {
    return <Object?>[
      entrypoint,
      width,
      height,
      title,
      level,
      transparent,
      decorated,
      resizable,
      ignoresMouseEvents,
      skipTaskbar,
      x,
      y,
    ];
  }

  Object encode() {
    return _toList();  }

  static KairoNativeWindowSpec decode(Object result) {
    result as List<Object?>;
    return KairoNativeWindowSpec(
      entrypoint: result[0]! as String,
      width: result[1]! as double,
      height: result[2]! as double,
      title: result[3]! as String,
      level: result[4]! as KairoNativeWindowLevel,
      transparent: result[5]! as bool,
      decorated: result[6]! as bool,
      resizable: result[7]! as bool,
      ignoresMouseEvents: result[8]! as bool,
      skipTaskbar: result[9]! as bool,
      x: result[10] as double?,
      y: result[11] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KairoNativeWindowSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(entrypoint, other.entrypoint) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(title, other.title) && _deepEquals(level, other.level) && _deepEquals(transparent, other.transparent) && _deepEquals(decorated, other.decorated) && _deepEquals(resizable, other.resizable) && _deepEquals(ignoresMouseEvents, other.ignoresMouseEvents) && _deepEquals(skipTaskbar, other.skipTaskbar) && _deepEquals(x, other.x) && _deepEquals(y, other.y);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KairoNativeWindowSpec(entrypoint: $entrypoint, width: $width, height: $height, title: $title, level: $level, transparent: $transparent, decorated: $decorated, resizable: $resizable, ignoresMouseEvents: $ignoresMouseEvents, skipTaskbar: $skipTaskbar, x: $x, y: $y)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is KairoNativeWindowLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is KairoNativeRect) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is KairoNativeWindowSpec) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : KairoNativeWindowLevel.values[value];
      case 130:
        return KairoNativeRect.decode(readValue(buffer)!);
      case 131:
        return KairoNativeWindowSpec.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// What Kairo asks the platform to do with windows.
///
/// Implemented natively — in Swift/AppKit on macOS, and later in Win32 and on
/// Linux. Every method is asynchronous: window operations cross to the platform
/// thread and must never block the isolate that asked.
class KairoNativeWindowApi {
  /// Constructor for [KairoNativeWindowApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KairoNativeWindowApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Creates a window from [spec] and returns the handle identifying it.
  ///
  /// The window is created hidden, so it can be positioned before anyone sees
  /// it. Call [showWindow] once it is ready.
  Future<int> createWindow(KairoNativeWindowSpec spec) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.createWindow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[spec]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Makes the window at [handle] visible.
  Future<void> showWindow(int handle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.showWindow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Hides the window at [handle] without destroying it.
  Future<void> hideWindow(int handle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.hideWindow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Destroys the window at [handle] and shuts down its engine.
  ///
  /// The handle is invalid afterwards.
  Future<void> closeWindow(int handle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.closeWindow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Brings the window at [handle] forward and gives it keyboard focus.
  Future<void> focusWindow(int handle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.focusWindow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Moves and resizes the window at [handle].
  Future<void> setWindowBounds(int handle, KairoNativeRect bounds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.setWindowBounds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle, bounds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// The current position and size of the window at [handle].
  Future<KairoNativeRect> getWindowBounds(int handle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.getWindowBounds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as KairoNativeRect;
  }

  /// Whether the window at [handle] is currently on screen.
  ///
  /// Asked of the platform rather than remembered on the Dart side, because the
  /// platform can hide a window without being told to — the user closing it,
  /// or the space it lives on going away.
  Future<bool> isWindowVisible(int handle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.isWindowVisible$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Changes where the window at [handle] sits in the stacking order.
  Future<void> setWindowLevel(int handle, KairoNativeWindowLevel level) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.setWindowLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle, level]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sets whether clicks fall through the window at [handle].
  Future<void> setIgnoresMouseEvents(int handle, bool ignore) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.setIgnoresMouseEvents$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handle, ignore]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// The usable area of the display the user is working on.
  ///
  /// The screen holding the keyboard focus, not a fixed one: a character that
  /// appeared on the display Kairo happened to launch on would be talking to an
  /// empty chair. Asked again every time it is needed, because the answer
  /// changes as the user moves between screens.
  ///
  /// Usable excludes the menu bar and the dock, so something standing on the
  /// bottom of this rectangle is standing on the desktop rather than behind the
  /// dock.
  Future<KairoNativeRect> activeDisplayBounds() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.activeDisplayBounds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as KairoNativeRect;
  }
}

/// What Kairo asks of the operating system itself, rather than of its windows.
class KairoNativeSystemApi {
  /// Constructor for [KairoNativeSystemApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KairoNativeSystemApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Whether the system starts Kairo when the user logs in.
  ///
  /// Asked of the system rather than remembered, because the user can revoke it
  /// in System Settings without Kairo being told, and a switch that shows what
  /// Kairo last wrote instead of what is true is a switch that lies.
  Future<bool> launchesAtLogin() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeSystemApi.launchesAtLogin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Asks the system to start Kairo at login, or to stop doing so.
  Future<void> setLaunchAtLogin(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeSystemApi.setLaunchAtLogin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// How one of Kairo's isolates reaches the others.
///
/// Every window Kairo creates runs its own `FlutterEngine`, and so its own
/// isolate: the main window and the character window are two Dart programs that
/// happen to share a process. They have no port, no memory and no event bus in
/// common, so the only path from one to the other is down to the platform and
/// back up again. This is that path.
///
/// The payload is text on purpose. The platform is a postman: it should not
/// need a new schema, and a rebuilt bridge, every time the application finds
/// something new to say. What the text means belongs to the application.
class KairoNativeRelayApi {
  /// Constructor for [KairoNativeRelayApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KairoNativeRelayApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Passes [message] to every Kairo isolate except the one that sent it.
  ///
  /// Broadcast rather than addressed, because Kairo has two isolates and
  /// addressing would mean teaching each of them the other's window handle for
  /// no gain. Delivery is best-effort: an isolate that is not listening yet
  /// misses the message rather than queueing it.
  Future<void> relay(String message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeRelayApi.relay$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// A message from another of Kairo's isolates.
abstract class KairoNativeRelay {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Another isolate sent [message].
  void onMessage(String message);

  static void setUp(KairoNativeRelay? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeRelay.onMessage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_message = args[0]! as String;
          try {
            api.onMessage(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

/// What the platform reports back about windows.
///
/// These arrive because the user or the operating system did something, not
/// because Kairo asked. The desktop engine translates them into events on the
/// bus.
abstract class KairoNativeWindowEvents {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// The window at [handle] was closed, by the user or by the platform.
  void onWindowClosed(int handle);

  /// The window at [handle] gained or lost keyboard focus.
  void onWindowFocusChanged(int handle, bool focused);

  /// The window at [handle] was moved or resized, and now occupies [bounds].
  void onWindowMoved(int handle, KairoNativeRect bounds);

  static void setUp(KairoNativeWindowEvents? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowEvents.onWindowClosed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_handle = args[0]! as int;
          try {
            api.onWindowClosed(arg_handle);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowEvents.onWindowFocusChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_handle = args[0]! as int;
          final bool arg_focused = args[1]! as bool;
          try {
            api.onWindowFocusChanged(arg_handle, arg_focused);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowEvents.onWindowMoved$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_handle = args[0]! as int;
          final KairoNativeRect arg_bounds = args[1]! as KairoNativeRect;
          try {
            api.onWindowMoved(arg_handle, arg_bounds);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
