// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum PlatformBridgePigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// How far forward a window sits in the platform's stacking order.
enum KairoNativeWindowLevel: Int, CaseIterable {
  /// An ordinary application window, ordered against its siblings by use.
  case normal = 0
  /// Above ordinary windows, including those of other applications. The
  /// character and reminder popups live here.
  case floating = 1
  /// Behind every ordinary window, pinned to the desktop.
  case desktop = 2
}

/// A rectangle in screen coordinates, in logical pixels.
///
/// A plain class rather than Flutter's `Rect`, because the generated Swift has
/// no access to Flutter's Dart types.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KairoNativeRect: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KairoNativeRect? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return KairoNativeRect(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
  static func == (lhs: KairoNativeRect, rhs: KairoNativeRect) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PlatformBridgePigeonInternal.deepEquals(lhs.x, rhs.x) && PlatformBridgePigeonInternal.deepEquals(lhs.y, rhs.y) && PlatformBridgePigeonInternal.deepEquals(lhs.width, rhs.width) && PlatformBridgePigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KairoNativeRect")
    PlatformBridgePigeonInternal.deepHash(value: x, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: y, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: width, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "KairoNativeRect(x: \(String(describing: x)), y: \(String(describing: y)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Everything the platform needs in order to create a window.
///
/// Every field is required: defaults belong to `KairoWindowDescriptor`, and a
/// schema that also carried them would be a second place for them to disagree.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KairoNativeWindowSpec: Hashable, CustomStringConvertible {
  /// The Dart entrypoint the window's own engine runs.
  ///
  /// Every window gets a separate `FlutterEngine`, and so a separate isolate.
  /// The named function must be annotated `@pragma('vm:entry-point')`, or the
  /// compiler will discard it from a release build.
  var entrypoint: String
  /// The window's initial width, in logical pixels.
  var width: Double
  /// The window's initial height, in logical pixels.
  var height: Double
  /// The window's title.
  ///
  /// Not drawn when [decorated] is false, but still what the platform reports
  /// to accessibility tools and window lists.
  var title: String
  /// Where the window sits in the stacking order.
  var level: KairoNativeWindowLevel
  /// Whether the window's background is transparent rather than opaque.
  var transparent: Bool
  /// Whether the platform draws a title bar and frame around the window.
  var decorated: Bool
  /// Whether the user may resize the window.
  var resizable: Bool
  /// Whether clicks fall through the window to whatever is behind it.
  var ignoresMouseEvents: Bool
  /// Whether the window is hidden from the dock, taskbar and window switcher.
  var skipTaskbar: Bool
  /// The initial left edge, in screen coordinates. Centred when null.
  var x: Double? = nil
  /// The initial top edge, in screen coordinates. Centred when null.
  var y: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KairoNativeWindowSpec? {
    let entrypoint = pigeonVar_list[0] as! String
    let width = pigeonVar_list[1] as! Double
    let height = pigeonVar_list[2] as! Double
    let title = pigeonVar_list[3] as! String
    let level = pigeonVar_list[4] as! KairoNativeWindowLevel
    let transparent = pigeonVar_list[5] as! Bool
    let decorated = pigeonVar_list[6] as! Bool
    let resizable = pigeonVar_list[7] as! Bool
    let ignoresMouseEvents = pigeonVar_list[8] as! Bool
    let skipTaskbar = pigeonVar_list[9] as! Bool
    let x: Double? = nilOrValue(pigeonVar_list[10])
    let y: Double? = nilOrValue(pigeonVar_list[11])

    return KairoNativeWindowSpec(
      entrypoint: entrypoint,
      width: width,
      height: height,
      title: title,
      level: level,
      transparent: transparent,
      decorated: decorated,
      resizable: resizable,
      ignoresMouseEvents: ignoresMouseEvents,
      skipTaskbar: skipTaskbar,
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      entrypoint,
      width,
      height,
      title,
      level,
      transparent,
      decorated,
      resizable,
      ignoresMouseEvents,
      skipTaskbar,
      x,
      y,
    ]
  }
  static func == (lhs: KairoNativeWindowSpec, rhs: KairoNativeWindowSpec) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PlatformBridgePigeonInternal.deepEquals(lhs.entrypoint, rhs.entrypoint) && PlatformBridgePigeonInternal.deepEquals(lhs.width, rhs.width) && PlatformBridgePigeonInternal.deepEquals(lhs.height, rhs.height) && PlatformBridgePigeonInternal.deepEquals(lhs.title, rhs.title) && PlatformBridgePigeonInternal.deepEquals(lhs.level, rhs.level) && PlatformBridgePigeonInternal.deepEquals(lhs.transparent, rhs.transparent) && PlatformBridgePigeonInternal.deepEquals(lhs.decorated, rhs.decorated) && PlatformBridgePigeonInternal.deepEquals(lhs.resizable, rhs.resizable) && PlatformBridgePigeonInternal.deepEquals(lhs.ignoresMouseEvents, rhs.ignoresMouseEvents) && PlatformBridgePigeonInternal.deepEquals(lhs.skipTaskbar, rhs.skipTaskbar) && PlatformBridgePigeonInternal.deepEquals(lhs.x, rhs.x) && PlatformBridgePigeonInternal.deepEquals(lhs.y, rhs.y)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KairoNativeWindowSpec")
    PlatformBridgePigeonInternal.deepHash(value: entrypoint, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: width, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: height, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: title, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: level, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: transparent, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: decorated, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: resizable, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: ignoresMouseEvents, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: skipTaskbar, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: x, hasher: &hasher)
    PlatformBridgePigeonInternal.deepHash(value: y, hasher: &hasher)
  }

  public var description: String {
    return "KairoNativeWindowSpec(entrypoint: \(String(describing: entrypoint)), width: \(String(describing: width)), height: \(String(describing: height)), title: \(String(describing: title)), level: \(String(describing: level)), transparent: \(String(describing: transparent)), decorated: \(String(describing: decorated)), resizable: \(String(describing: resizable)), ignoresMouseEvents: \(String(describing: ignoresMouseEvents)), skipTaskbar: \(String(describing: skipTaskbar)), x: \(String(describing: x)), y: \(String(describing: y)))"
  }
}

private class PlatformBridgePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KairoNativeWindowLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return KairoNativeRect.fromList(self.readValue() as! [Any?])
    case 131:
      return KairoNativeWindowSpec.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PlatformBridgePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? KairoNativeWindowLevel {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? KairoNativeRect {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? KairoNativeWindowSpec {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PlatformBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PlatformBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PlatformBridgePigeonCodecWriter(data: data)
  }
}

class PlatformBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PlatformBridgePigeonCodec(readerWriter: PlatformBridgePigeonCodecReaderWriter())
}


/// What Kairo asks the platform to do with windows.
///
/// Implemented natively — in Swift/AppKit on macOS, and later in Win32 and on
/// Linux. Every method is asynchronous: window operations cross to the platform
/// thread and must never block the isolate that asked.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KairoNativeWindowApi {
  /// Creates a window from [spec] and returns the handle identifying it.
  ///
  /// The window is created hidden, so it can be positioned before anyone sees
  /// it. Call [showWindow] once it is ready.
  func createWindow(spec: KairoNativeWindowSpec, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Makes the window at [handle] visible.
  func showWindow(handle: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Hides the window at [handle] without destroying it.
  func hideWindow(handle: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Destroys the window at [handle] and shuts down its engine.
  ///
  /// The handle is invalid afterwards.
  func closeWindow(handle: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Brings the window at [handle] forward and gives it keyboard focus.
  func focusWindow(handle: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Moves and resizes the window at [handle].
  func setWindowBounds(handle: Int64, bounds: KairoNativeRect, completion: @escaping (Result<Void, Error>) -> Void)
  /// The current position and size of the window at [handle].
  func getWindowBounds(handle: Int64, completion: @escaping (Result<KairoNativeRect, Error>) -> Void)
  /// Whether the window at [handle] is currently on screen.
  ///
  /// Asked of the platform rather than remembered: it can hide a window without
  /// being told to, when the user closes it or its space goes away.
  func isWindowVisible(handle: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Changes where the window at [handle] sits in the stacking order.
  func setWindowLevel(handle: Int64, level: KairoNativeWindowLevel, completion: @escaping (Result<Void, Error>) -> Void)
  /// Sets whether clicks fall through the window at [handle].
  func setIgnoresMouseEvents(handle: Int64, ignore: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  /// The usable area of the display the user is working on — the screen holding
  /// keyboard focus, not the one Kairo launched on.
  ///
  /// Usable excludes the menu bar and the dock, so something placed on the
  /// bottom edge of this rectangle sits on the desktop rather than behind the
  /// dock.
  func activeDisplayBounds(completion: @escaping (Result<KairoNativeRect, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KairoNativeWindowApiSetup {
  static var codec: FlutterStandardMessageCodec { PlatformBridgePigeonCodec.shared }
  /// Sets up an instance of `KairoNativeWindowApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KairoNativeWindowApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Creates a window from [spec] and returns the handle identifying it.
    ///
    /// The window is created hidden, so it can be positioned before anyone sees
    /// it. Call [showWindow] once it is ready.
    let createWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.createWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createWindowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let specArg = args[0] as! KairoNativeWindowSpec
        api.createWindow(spec: specArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createWindowChannel.setMessageHandler(nil)
    }
    /// Makes the window at [handle] visible.
    let showWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.showWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showWindowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.showWindow(handle: handleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showWindowChannel.setMessageHandler(nil)
    }
    /// Hides the window at [handle] without destroying it.
    let hideWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.hideWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hideWindowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.hideWindow(handle: handleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      hideWindowChannel.setMessageHandler(nil)
    }
    /// Destroys the window at [handle] and shuts down its engine.
    ///
    /// The handle is invalid afterwards.
    let closeWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.closeWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeWindowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.closeWindow(handle: handleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeWindowChannel.setMessageHandler(nil)
    }
    /// Brings the window at [handle] forward and gives it keyboard focus.
    let focusWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.focusWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      focusWindowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.focusWindow(handle: handleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      focusWindowChannel.setMessageHandler(nil)
    }
    /// Moves and resizes the window at [handle].
    let setWindowBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.setWindowBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWindowBoundsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        let boundsArg = args[1] as! KairoNativeRect
        api.setWindowBounds(handle: handleArg, bounds: boundsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setWindowBoundsChannel.setMessageHandler(nil)
    }
    /// The current position and size of the window at [handle].
    let getWindowBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.getWindowBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWindowBoundsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.getWindowBounds(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getWindowBoundsChannel.setMessageHandler(nil)
    }
    /// Whether the window at [handle] is currently on screen.
    ///
    /// Asked of the platform rather than remembered: it can hide a window without
    /// being told to, when the user closes it or its space goes away.
    let isWindowVisibleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.isWindowVisible\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWindowVisibleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.isWindowVisible(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isWindowVisibleChannel.setMessageHandler(nil)
    }
    /// Changes where the window at [handle] sits in the stacking order.
    let setWindowLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.setWindowLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWindowLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        let levelArg = args[1] as! KairoNativeWindowLevel
        api.setWindowLevel(handle: handleArg, level: levelArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setWindowLevelChannel.setMessageHandler(nil)
    }
    /// Sets whether clicks fall through the window at [handle].
    let setIgnoresMouseEventsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.setIgnoresMouseEvents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIgnoresMouseEventsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        let ignoreArg = args[1] as! Bool
        api.setIgnoresMouseEvents(handle: handleArg, ignore: ignoreArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setIgnoresMouseEventsChannel.setMessageHandler(nil)
    }
    /// The usable area of the display the user is working on — the screen holding
    /// keyboard focus, not the one Kairo launched on.
    ///
    /// Usable excludes the menu bar and the dock, so something placed on the
    /// bottom edge of this rectangle sits on the desktop rather than behind the
    /// dock.
    let activeDisplayBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowApi.activeDisplayBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activeDisplayBoundsChannel.setMessageHandler { _, reply in
        api.activeDisplayBounds { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      activeDisplayBoundsChannel.setMessageHandler(nil)
    }
  }
}
/// What Kairo asks of the operating system itself, rather than of its windows.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KairoNativeSystemApi {
  /// Whether the system starts Kairo when the user logs in.
  ///
  /// Asked of the system rather than remembered: the user can revoke it in
  /// System Settings without Kairo being told.
  func launchesAtLogin(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Asks the system to start Kairo at login, or to stop doing so.
  func setLaunchAtLogin(enabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KairoNativeSystemApiSetup {
  static var codec: FlutterStandardMessageCodec { PlatformBridgePigeonCodec.shared }
  /// Sets up an instance of `KairoNativeSystemApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KairoNativeSystemApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether the system starts Kairo when the user logs in.
    ///
    /// Asked of the system rather than remembered: the user can revoke it in
    /// System Settings without Kairo being told.
    let launchesAtLoginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeSystemApi.launchesAtLogin\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchesAtLoginChannel.setMessageHandler { _, reply in
        api.launchesAtLogin { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      launchesAtLoginChannel.setMessageHandler(nil)
    }
    /// Asks the system to start Kairo at login, or to stop doing so.
    let setLaunchAtLoginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeSystemApi.setLaunchAtLogin\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLaunchAtLoginChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.setLaunchAtLogin(enabled: enabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLaunchAtLoginChannel.setMessageHandler(nil)
    }
  }
}
/// How one of Kairo's isolates reaches the others.
///
/// Kairo's windows share no memory and no event bus, so the only path between
/// them is down to the platform and back up. This is that path.
///
/// The payload is text on purpose: the platform is a postman, and should not
/// need a rebuilt bridge every time the application finds something new to say.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KairoNativeRelayApi {
  /// Passes [message] to every Kairo isolate except the one that sent it.
  ///
  /// Broadcast rather than addressed. Delivery is best-effort: an isolate not
  /// yet listening misses the message rather than queueing it.
  func relay(message: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KairoNativeRelayApiSetup {
  static var codec: FlutterStandardMessageCodec { PlatformBridgePigeonCodec.shared }
  /// Sets up an instance of `KairoNativeRelayApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KairoNativeRelayApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Passes [message] to every Kairo isolate except the one that sent it.
    ///
    /// Broadcast rather than addressed. Delivery is best-effort: an isolate not
    /// yet listening misses the message rather than queueing it.
    let relayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeRelayApi.relay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      relayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        api.relay(message: messageArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      relayChannel.setMessageHandler(nil)
    }
  }
}

/// A message from another of Kairo's isolates.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol KairoNativeRelayProtocol {
  /// Another isolate sent [message].
  func onMessage(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class KairoNativeRelay: KairoNativeRelayProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PlatformBridgePigeonCodec {
    return PlatformBridgePigeonCodec.shared
  }
  /// Another isolate sent [message].
  func onMessage(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeRelay.onMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}

/// What the platform reports back about windows.
///
/// These arrive because the user or the operating system did something, not
/// because Kairo asked. The desktop engine translates them into events on the
/// bus.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol KairoNativeWindowEventsProtocol {
  /// The window at [handle] was closed, by the user or by the platform.
  func onWindowClosed(handle handleArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The window at [handle] gained or lost keyboard focus.
  func onWindowFocusChanged(handle handleArg: Int64, focused focusedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The window at [handle] was moved or resized, and now occupies [bounds].
  func onWindowMoved(handle handleArg: Int64, bounds boundsArg: KairoNativeRect, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class KairoNativeWindowEvents: KairoNativeWindowEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PlatformBridgePigeonCodec {
    return PlatformBridgePigeonCodec.shared
  }
  /// The window at [handle] was closed, by the user or by the platform.
  func onWindowClosed(handle handleArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowEvents.onWindowClosed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// The window at [handle] gained or lost keyboard focus.
  func onWindowFocusChanged(handle handleArg: Int64, focused focusedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowEvents.onWindowFocusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, focusedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// The window at [handle] was moved or resized, and now occupies [bounds].
  func onWindowMoved(handle handleArg: Int64, bounds boundsArg: KairoNativeRect, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kairo_desktop_engine.KairoNativeWindowEvents.onWindowMoved\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, boundsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
